const TYPES = {
    ADD_MESSAGE: 'ADD_MESSAGE',
    ADD_PARTICIPANT: 'ADD_PARTICIPANT',
    REMOVE_PARTICIPANT: 'REMOVE_PARTICIPANT',
    SET_USERNAME: 'SET_USERNAME',
    SET_ROOM: 'SET_ROOM',
}

export default TYPES;
