export default {
    RESET_LOBBY: 'RESET_LOBBY',
    ADD_MESSAGE: 'ADD_MESSAGE',
    ADD_SONG: 'ADD_SONG',
    ADD_PARTICIPANT: 'ADD_PARTICIPANT',
    REMOVE_PARTICIPANT: 'REMOVE_PARTICIPANT',
    SET_USERNAME: 'SET_USERNAME',
    SET_CONNECTED: 'SET_CONNECTED',
}
