export default {
    PLAY: 'PLAY',
    PAUSE: 'PAUSE',
    TOGGLE_PLAYING: 'TOGGLE_PLAYING',
    SET_AUDIO_LEVEL: 'SET_AUDIO_LEVEL',
    SET_PROGRESS: 'SET_PROGRESS',
    SET_SONG: 'SET_SONG',
    SET_READY: 'SET_READY',
}