export default {
    SET_PLAYING: 'SET_PLAYING',
    TOGGLE_PLAYING: 'TOGGLE_PLAYING',
    SET_AUDIO_LEVEL: 'SET_AUDIO_LEVEL',
    SET_PROGRESS: 'SET_PROGRESS',
    SET_SONG: 'SET_SONG',
    SET_READY: 'SET_READY',
    SET_DURATION: "SET_DURATION",
    ADD_SONG: 'ADD_SONG',
    SET_SONGS: 'SET_SONGS',
}
